Updated Readme
Redot-Engine/redot-engine pull request #16
Opened 2024-09-30 21:28 UTC by MadMax1960

2024-09-30 22:50 UTC, Tekisasu-JohnK commented
Eeesh

2024-10-01 15:02 UTC, RadiantUwU approved these changes

2024-10-01 20:09 UTC, Timo654 approved these changes

2024-10-03 00:25 UTC, dandykong requested changes

2024-10-03 00:25 UTC, dandykong commented on README.md
> +# Wokedot Engine
Good lord, I hope this repo has branch protection.

2024-10-10 12:06 UTC, RadenTheFolf reviewed
These changes have been addressed through pull request: https://github.com/Redot-Engine/redot-engine/pull/627

As such this pr can be closed.

2024-10-10 15:04 UTC, RadenTheFolf commented
These changes have been addressed through pull request: https://github.com/Redot-Engine/redot-engine/pull/627

2024-10-10 15:04 UTC, closed without merging